### ISSUE TITLE
Port names not shown in Nagios warning

### ISSUE THREAD

**Issue by ghost** [Cybso/check_poodle#1]
The vulnerable port names are shown in Nagios's (v3) warnings. I guess this line is supposed included the port information in the message but it does not: https://github.com/Cybso/check_poodle/blob/master/bin/check_poodle#L82

This can be fixed by appending $1 to the previous echo statement:
```sh
warn() {
    if [ "$RESULT" = "0" ]; then
        RESULT=1
        echo "SSLv2/SSLv3 accepted on the following ports: $1"
    fi
    echo "  $1"
    RESULT=$RESULT_MATCH
}
```

**Comment by Cybso** [comment]
No, this would only show the first affected port (and this twice, if you have a look at the details).

I've fixed that by printing the ports without newline.
